### ISSUE TITLE
Add example and notebook for the Brazilian presalt deep water model

### ISSUE THREAD

**Issue by SouzaEM** [Olender/spyro-1#48]
TotalEnergies provided a model for the Brazilian presalt and it would be interesting to check how our current acoustic solvers perform on this model. Then, this issue involves the implementation of an example that runs the forward acoustic model for the Brazilian presalt deep water model provided by TotalEnergies. Also, notebook explaining how to run this example will be added.

**Comment by Olender** [comment]
Do we have permission from Total for this example to be made public? If not, the notebook needs to be on the private repository

**Comment by SouzaEM** [comment]
I will keep the development in a private repository until we check if the example may be made public. Thank you for the remark.
